apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibonjour1234-ceaee
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/ibonjour1234-ceaee.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ibonjour1234-ceaee
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
